### ISSUE TITLE
text/occi rendering case sensitive

### ISSUE THREAD

**Issue by jeanparpaillon** [Misenko/jOCCI-core#1]
Hi,
It seems the text/occi rendering is implemented case-sensitive for headers name.
In RFC 2616 (http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), field names are case insensitive.

Could we align jOCCI on this ?

**Comment by Misenko** [comment]
Hi,
I've just released new version of both jOCCI-core and jOCCI-api (0.2.2) that should fix this issue. Can you please test it and let me know?

**Comment by jeanparpaillon** [comment]
Thanks ! I will let you know as soon as I have tested
